experiment_name: sage_zinc

# Model specific arguments/hyperparameters
model: GraphSAGE
model_args:
  hidden_channels: 256
  out_channels: 256
  num_layers: 9
  num_pred_layers: 3
  dropout: 0.0389364
  readout: attention
  residual: true

# Dataset specific arguments/hyperparameters
dataset: ZINC
data_args:
  root: data/zinc/
  batch_size: 512

# Training specific arguments/hyperparameters
cuda: 1
seed: 42
train_args:
  runs: 3
  epochs: 150
  eval_interval: 10
  loss_fn: L1Loss
  optimizer: Adam
  optimizer_kwargs:
    lr: 0.000202783
    weight_decay: 2.80988e-06
  scheduler: ReduceLROnPlateau
  scheduler_kwargs:
    mode: min
  evaluator: ZINCEvaluator
checkpoint_dir: out/checkpoints/
log_dir: out/logs/
