experiment_name: vpa_hiv

# Model specific arguments/hyperparameters
model: GNN-VPA
model_args:
  hidden_channels: 256
  out_channels: 256
  num_layers: 9
  num_trans_layers: 1
  num_pred_layers: 3
  eps: 0.0
  train_eps: True
  dropout: 0.104699
  readout: attention
  residual: true

# Dataset specific arguments/hyperparameters
dataset: ogbg-molhiv
data_args:
  root: data/
  batch_size: 256

# Training specific arguments/hyperparameters
cuda: 2
seed: 42
train_args:
  runs: 5
  epochs: 150
  eval_interval: 10
  loss_fn: BCEWithLogitsLoss
  optimizer: Adam
  optimizer_kwargs:
    lr: 0.00037377
    weight_decay: 1.19838e-05
  scheduler: ReduceLROnPlateau
  scheduler_kwargs:
    mode: max
  evaluator: OGBGraphPropPredEvaluator
  evaluator_kwargs:
    name: ogbg-molhiv
checkpoint_dir: out/checkpoints/
log_dir: out/logs/
